### ISSUE TITLE
Error reading Config: While parsing config: yaml: line 6: did not find expected '-' indicator

### ISSUE THREAD

**Issue by marove2000** [carlosz1986/paperless-mailservice#30]
Hello carlosz,

thank you for this handy tool (according to the variable-names "DATEV" we could also speak German I think ^^). I would like to use your tool but unfortunately I'm running into following erorr:

```
Attaching to paperless-mailservice-1
paperless-mailservice-1  | 2024/12/18 16:10:08 Error reading Config: While parsing config: yaml: line 6: did not find expected '-' indicator
paperless-mailservice-1 exited with code 1
```

The error is reproducable. I've used these commands:

- git clone https://github.com/carlosz1986/paperless-mailservice.git
- cd paperless-mailservice
- cd config
- cp config.yaml.example config.yaml
- cd ..
- docker compose up

I've also tried to change the config but this does not seem to work. I've also tried docker compose up --build but this does also not work.

Used System: Ubuntu 24.04.1 LTS (latest patch level)

Can you please help?

Regards from Regensburg
Timo

**Comment by carlosz1986** [comment]
Hi Timo,
Yes German would be also fine ;-) 
The problem occurs, because the example config has a missing \t in line 6 & 13 ... I was never using the example config and have not seen the issue. Version Tag 1.3 should be stable. Anyway...  I will fix it soon...

Sorry, Hope you get it working soon :-)

best,
